import { chromium } from '../../docs/node_modules/playwright/index.mjs';
const URL = process.env.SPIKE_URL || 'http://localhost:4322/ai-training/spike/terminal/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
await page.goto(URL);
await page.waitForFunction(() => window.__session, null, { timeout: 15000 });
console.log('session:', await page.evaluate(() => window.__session.id + ' ' + window.__session.cwd));
await page.waitForTimeout(5000);
await page.click('#btn-screen'); await page.waitForTimeout(500);
console.log('--- attached screen ---\n' + (await page.evaluate(() => window.__lastScreen)).split('\n').slice(-8).join('\n'));
await page.click('#btn-type'); await page.waitForTimeout(25000);
await page.click('#btn-conv'); await page.waitForTimeout(500);
console.log('--- conversation from transcript ---\n' + (await page.evaluate(() => window.__lastConv.map(t => t.role + ': ' + t.text.slice(0, 160)).join('\n'))));
await page.click('#btn-coach');
await page.waitForFunction(() => window.__lastCoach, null, { timeout: 90000 });
console.log('--- coach ---\n' + JSON.stringify(await page.evaluate(() => window.__lastCoach), null, 2));
await page.waitForTimeout(500);
await page.screenshot({ path: 'attach-coach.png', fullPage: true });
await browser.close();
