import { chromium } from '../../docs/node_modules/playwright/index.mjs';
const URL = 'http://localhost:4322/ai-training/spike/terminal/?token=' + (process.env.SPIKE_TOKEN || 'testtoken');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on('console', (m) => m.type() === 'error' && console.log('browser:', m.text()));
await page.goto(URL);
await page.waitForFunction(() => document.getElementById('spike-term-status').textContent === 'attached', null, { timeout: 15000 });
console.log('url after token strip:', page.url());
await page.waitForTimeout(4000);
console.log('term size:', await page.evaluate(() => { const r = document.getElementById('spike-term').getBoundingClientRect(); return `${Math.round(r.width)}x${Math.round(r.height)} cols=${window.__spike.term.cols} rows=${window.__spike.term.rows}`; }));
console.log('right rail hidden:', await page.evaluate(() => !document.querySelector('.right-sidebar-container') || getComputedStyle(document.querySelector('.right-sidebar-container')).display === 'none'));
console.log('sidebar link:', await page.evaluate(() => !!document.querySelector('nav a[href$="/spike/terminal/"]')));
await page.selectOption('#sel-theme', 'light'); await page.waitForTimeout(500); await page.click('#btn-screen'); await page.waitForTimeout(400); console.log('--- attached screen ---\n' + (await page.evaluate(() => window.__lastScreen)).split('\n').filter(Boolean).slice(-6).join('\n'));
await page.screenshot({ path: 'ui-light.png' });
await page.click('#btn-type'); await page.waitForTimeout(1500);
await page.click('#btn-screen'); await page.waitForTimeout(400);
const scr = await page.evaluate(() => window.__lastScreen);
console.log('typed without enter (prompt still in input box):', /❯\s+Explain in two sentences/.test(scr), '| no answer yet:', !/⏺/.test(scr.split('Explain in two sentences').pop() || ''));
await page.evaluate(() => window.__spike.send({ type: 'in', data: '\r' }));
await page.waitForTimeout(20000);
await page.click('#btn-coach');
await page.waitForFunction(() => window.__lastCoach, null, { timeout: 90000 });
await page.waitForTimeout(500);
await page.screenshot({ path: 'ui-light-coach.png' });
await page.selectOption('#sel-theme', 'dark'); await page.waitForTimeout(500);
await page.screenshot({ path: 'ui-dark.png' });
console.log('coach:', (await page.evaluate(() => window.__lastCoach.tip)).slice(0, 160));
await browser.close();
